PORTNAME=	libsfmbasisapi
DISTVERSION=	0.1.15
CATEGORIES=	devel
USE_GITHUB=	yes
GH_ACCOUNT=	leakingmemory

LICENSE=	AGPLv3

MAINTAINER=	sigsegv@raditoube.org
COMMENT=	Unofficial library for communicating with SFM basisapi
WWW=		https://github.com/leakingmemory/libsfmbasisapi/

USES=		cmake ssl

LIB_DEPENDS=	libcpprest.so:devel/cpprestsdk

#USE_GCC=	11
#CFLAGS+=	-I/usr/local/include

.include <bsd.port.mk>
