PORTNAME=	libsfmbasisapi
DISTVERSION=	0.4.3
CATEGORIES=	devel
USE_GITHUB=	yes
GH_ACCOUNT=	leakingmemory

LICENSE=	AGPLv3

MAINTAINER=	sigsegv@raditoube.org
COMMENT=	Unofficial library for communicating with SFM basisapi
WWW=		https://github.com/leakingmemory/libsfmbasisapi/

BUILD_DEPENDS=	/usr/local/include/nlohmann/json.hpp:devel/nlohmann-json

USES=		cmake ssl

#USE_GCC=	11
#CFLAGS+=	-I/usr/local/include

.include <bsd.port.mk>
